--CHAPTER 3 - DATA DEFINITION LANGUAGE
-- CREATE A NEW TABLE PERSONS WITH COLUMN ID,person_name,birth_date and phone
CREATE TABLE persons (
id INT NOT NULL,persons_name VARCHAR(50) NOT NULL,birth_date DATE,phone VARCHAR(50) NOT NULL, CONSTRAINT pk_persons PRIMARY KEY(id)
)
--TASK 1- ADD NEW COLUMN EMAIL TO THE TABLE PERSONS
ALTER TABLE persons ADD email VARCHAR(50) NOT NULL;
--TASK2 2-REMOVE THE COLUMN PHONE FROM THE PERSONS TABLE
