--CHAPTER 4 - DATA MANUPULATION LANGUAGE

--METHOD 1 OF INSERTING DATA INTO TABLES
INSERT INTO customers  (id,first_name,country,score)
VALUES (6,'Anna','USA',NULL),
       (7,'Sam',NULL,100),
      (8,'USA','MAX',NULL),
       (9,'Andreas','Germany',null),
       (10,'Sahra',null,null)
--METHOD 2- INSERTING DATA INTO TABLES FROM ANOTHER TABLE CALLED SOURCE TABLE
INSERT INTO persons (id,persons_name,birth_date,phone)
SELECT id,first_name,null,'unknown' from customers

--TASK 1-CHANGE THE SCORE OF CUSTOMER 6 TO 0
UPDATE customers SET score=0 WHERE ID =6;
--TASK 2- CHANGE THE SCORE OF CUSTOMER WITH ID 10 TO 0 AND UPDATE THE COUNTRY TO UK
UPDATE customers SET score=0,country='UK' WHERE id=10;
--TASK 3 - UPDATE CUSTOMER WITH A NULL SCORE BY SETTING THEIR SCORE TO 0
UPDATE customers SET Score=0 WHERE score is NULL;
--TASK 4 -DELETE ALL CUSTOMERS WITH AN ID >5
DELETE FROM customers where id >5;
--TASK 5- DELETE ALL DATA FROM TABLE PERSONS
DELETE FROM persons;




