--CHAPTER 3 - DATA DEFINITION LANGUAGE

-- TASK 1-CREATE A NEW TABLE PERSONS WITH COLUMN ID,person_name,birth_date and phone
CREATE TABLE persons (
id INT NOT NULL,persons_name VARCHAR(50) NOT NULL,birth_date DATE,phone VARCHAR(50) NOT NULL, CONSTRAINT pk_persons PRIMARY KEY(id)
)
--TASK 2- ADD NEW COLUMN EMAIL TO THE TABLE PERSONS
ALTER TABLE persons ADD email VARCHAR(50) NOT NULL;
--TASK2 3-REMOVE THE COLUMN PHONE FROM THE PERSONS TABLE
ALTER TABLE persons DROP COLUMN phone;
--TASK 4 -DELETE TABLE PERSONS FROM THE DATABASE
DROP TABLE persons;
